use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("workspace root")
        .to_path_buf()
}

struct Fixture {
    root: PathBuf,
}

impl Fixture {
    fn new(name: &str) -> Self {
        let root = std::env::temp_dir().join(format!(
            "agentd-release-check-{name}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .expect("system time should be after unix epoch")
                .as_nanos()
        ));
        fs::create_dir_all(&root).expect("fixture root should be created");
        Self { root }
    }

    fn write(&self, relative: &str, contents: &str) {
        let path = self.root.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("fixture parent should be created");
        }
        fs::write(path, contents).expect("fixture file should be written");
    }

    fn install_release_check(&self) -> PathBuf {
        let source = workspace_root().join("scripts/release-check");
        let destination = self.root.join("scripts/release-check");
        fs::create_dir_all(destination.parent().expect("script parent"))
            .expect("script parent should be created");
        fs::copy(source, &destination).expect("release-check script should exist");
        fs::set_permissions(&destination, fs::Permissions::from_mode(0o755))
            .expect("release-check script should be executable");
        destination
    }

    fn run_release_check(&self, args: &[&str]) -> Output {
        Command::new("bash")
            .arg(self.root.join("scripts/release-check"))
            .args(args)
            .current_dir(&self.root)
            .output()
            .expect("release-check should run")
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.root);
    }
}

fn valid_fixture(name: &str, version: &str) -> Fixture {
    let fixture = Fixture::new(name);
    fixture.write(
        "Cargo.toml",
        &format!(
            r#"[workspace]
members = [
    "crates/agentd",
    "crates/agentd-runner",
    "crates/agentd-scheduler",
]

[workspace.package]
version = "{version}"
"#
        ),
    );
    fixture.write(
        "Cargo.lock",
        &format!(
            r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "agentd"
version = "{version}"

[[package]]
name = "agentd-runner"
version = "{version}"

[[package]]
name = "agentd-scheduler"
version = "{version}"
"#
        ),
    );
    for crate_name in ["agentd", "agentd-runner", "agentd-scheduler"] {
        fixture.write(
            &format!("crates/{crate_name}/Cargo.toml"),
            &format!(
                r#"[package]
name = "{crate_name}"
version.workspace = true
"#
            ),
        );
        fixture.write(&format!("crates/{crate_name}/src/lib.rs"), "");
    }
    fixture.write(
        "CHANGELOG.md",
        &format!(
            r#"# Changelog

## [Unreleased]

## [{version}] — 2026-05-07

### Added

- Release ceremony tooling.
"#
        ),
    );
    fixture.write(
        "Containerfile",
        r#"ARG AGENTD_REF=local
LABEL org.tesserine.agentd.ref="${AGENTD_REF}"
COPY --from=builder /workspace/target/release/agentd /usr/local/bin/agentd
"#,
    );
    fixture.write(
        ".github/workflows/release.yml",
        r#"name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate release tag
        run: ./scripts/release-check release "$GITHUB_REF_NAME"

      - name: Install container tooling
        run: sudo apt-get install -y podman
"#,
    );
    fixture.install_release_check();
    fixture
}

fn workspace_manifest_with_members(version: &str, members: &[&str]) -> String {
    let members = members
        .iter()
        .map(|member| format!("    \"{member}\","))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"[workspace]
members = [
{members}
]

[workspace.package]
version = "{version}"
"#
    )
}

fn cargo_lock_with_packages(packages: &[(&str, &str)]) -> String {
    let packages = packages
        .iter()
        .map(|(name, package_version)| {
            format!(
                r#"[[package]]
name = "{name}"
version = "{package_version}"
"#
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"# This file is automatically @generated by Cargo.
version = 4

{packages}
"#
    )
}

fn assert_success(output: &Output) {
    assert!(
        output.status.success(),
        "command failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

fn assert_failure_contains(output: &Output, expected: &str) {
    assert!(
        !output.status.success(),
        "command unexpectedly succeeded\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains(expected),
        "stderr did not contain {expected:?}\nstderr:\n{stderr}"
    );
}

#[test]
fn metadata_accepts_a_coherent_agentd_release_surface() {
    let fixture = valid_fixture("metadata-success", "1.2.3");

    let output = fixture.run_release_check(&["metadata"]);

    assert_success(&output);
}

#[test]
fn metadata_accepts_canonical_semver_release_versions() {
    for version in ["0.0.0", "1.2.3-rc.1"] {
        let fixture = valid_fixture(&format!("metadata-canonical-{version}"), version);

        let output = fixture.run_release_check(&["metadata"]);

        assert_success(&output);
    }
}

#[test]
fn metadata_rejects_a_missing_workspace_version() {
    let fixture = valid_fixture("metadata-missing-version", "1.2.3");
    fixture.write(
        "Cargo.toml",
        r#"[workspace]
members = ["crates/agentd"]

[workspace.package]
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(&output, "workspace package version not found");
}

#[test]
fn metadata_rejects_workspace_package_versions_drifted_in_cargo_lock() {
    let fixture = valid_fixture("metadata-lock-version-drift", "1.2.3");
    fixture.write(
        "Cargo.lock",
        r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "agentd"
version = "1.2.4"
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        "Cargo.lock package agentd version 1.2.4 does not match workspace version 1.2.3",
    );
}

#[test]
fn metadata_rejects_new_workspace_members_that_do_not_inherit_the_workspace_version() {
    let fixture = valid_fixture("metadata-extra-member-version-inherit", "1.2.3");
    fixture.write(
        "Cargo.toml",
        &workspace_manifest_with_members(
            "1.2.3",
            &[
                "crates/agentd",
                "crates/agentd-runner",
                "crates/agentd-scheduler",
                "crates/agentd-extra",
            ],
        ),
    );
    fixture.write(
        "crates/agentd-extra/Cargo.toml",
        r#"[package]
name = "agentd-extra"
version = "1.2.3"
"#,
    );
    fixture.write("crates/agentd-extra/src/lib.rs", "");

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        "crates/agentd-extra/Cargo.toml must inherit version.workspace = true",
    );
}

#[test]
fn metadata_checks_cargo_lock_versions_for_new_workspace_members() {
    let fixture = valid_fixture("metadata-extra-member-lock-drift", "1.2.3");
    fixture.write(
        "Cargo.toml",
        &workspace_manifest_with_members(
            "1.2.3",
            &[
                "crates/agentd",
                "crates/agentd-runner",
                "crates/agentd-scheduler",
                "crates/agentd-extra",
            ],
        ),
    );
    fixture.write(
        "crates/agentd-extra/Cargo.toml",
        r#"[package]
name = "agentd-extra"
version.workspace = true
"#,
    );
    fixture.write("crates/agentd-extra/src/lib.rs", "");
    fixture.write(
        "Cargo.lock",
        &cargo_lock_with_packages(&[
            ("agentd", "1.2.3"),
            ("agentd-runner", "1.2.3"),
            ("agentd-scheduler", "1.2.3"),
            ("agentd-extra", "9.9.9"),
        ]),
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        "Cargo.lock package agentd-extra version 9.9.9 does not match workspace version 1.2.3",
    );
}

#[test]
fn metadata_extracts_workspace_versions_with_comments_and_whitespace() {
    let fixture = valid_fixture("metadata-version-formatting", "1.2.3");
    fixture.write(
        "Cargo.toml",
        r#"[workspace]
members = [
    "crates/agentd",
    "crates/agentd-runner",
    "crates/agentd-scheduler",
]

[workspace.package] # shared package substrate
  version   =   "1.2.3" # release identity
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_success(&output);
}

#[test]
fn metadata_rejects_malformed_changelog_release_headings() {
    let fixture = valid_fixture("metadata-malformed-changelog", "1.2.3");
    fixture.write(
        "CHANGELOG.md",
        r#"# Changelog

## [Unreleased]

## [1.2.3] - 2026-05-07
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(&output, "release heading is malformed");
}

#[test]
fn metadata_rejects_unsupported_workspace_prerelease_versions() {
    let fixture = valid_fixture("metadata-unsupported-workspace-prerelease", "1.2.3-beta.1");

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(
        &output,
        "workspace version must look like X.Y.Z or X.Y.Z-rc.N: 1.2.3-beta.1",
    );
}

#[test]
fn metadata_rejects_workspace_versions_with_noncanonical_numeric_components() {
    for version in ["01.2.3", "1.02.3", "1.2.03", "1.2.3-rc.01", "1.2.3-rc.0"] {
        let fixture = valid_fixture(&format!("metadata-noncanonical-{version}"), version);

        let output = fixture.run_release_check(&["metadata"]);

        assert_failure_contains(
            &output,
            &format!("workspace version must look like X.Y.Z or X.Y.Z-rc.N: {version}"),
        );
    }
}

#[test]
fn metadata_rejects_unsupported_changelog_prerelease_headings() {
    let fixture = valid_fixture("metadata-unsupported-changelog-prerelease", "1.2.3");
    fixture.write(
        "CHANGELOG.md",
        r#"# Changelog

## [Unreleased]

## [1.2.3-beta.1] — 2026-05-07
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(&output, "release heading is malformed");
}

#[test]
fn metadata_rejects_changelog_headings_with_noncanonical_numeric_components() {
    for version in ["01.2.3", "1.02.3", "1.2.03", "1.2.3-rc.01", "1.2.3-rc.0"] {
        let fixture = valid_fixture(
            &format!("metadata-changelog-noncanonical-{version}"),
            "1.2.3",
        );
        fixture.write(
            "CHANGELOG.md",
            &format!(
                r#"# Changelog

## [Unreleased]

## [{version}] — 2026-05-07
"#
            ),
        );

        let output = fixture.run_release_check(&["metadata"]);

        assert_failure_contains(&output, "release heading is malformed");
    }
}

#[test]
fn metadata_rejects_release_workflows_without_early_tag_validation() {
    let fixture = valid_fixture("metadata-workflow-missing-validation", "1.2.3");
    fixture.write(
        ".github/workflows/release.yml",
        r#"name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install container tooling
        run: sudo apt-get install -y podman
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(&output, "validate the release tag before container setup");
}

#[test]
fn metadata_rejects_release_workflows_that_validate_tags_after_container_setup() {
    let fixture = valid_fixture("metadata-workflow-late-validation", "1.2.3");
    fixture.write(
        ".github/workflows/release.yml",
        r#"name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install container tooling
        run: sudo apt-get install -y podman

      - name: Validate release tag
        run: ./scripts/release-check release "$GITHUB_REF_NAME"
"#,
    );

    let output = fixture.run_release_check(&["metadata"]);

    assert_failure_contains(&output, "validate the release tag before container setup");
}

#[test]
fn notes_emit_the_matching_changelog_section_without_outer_blank_lines() {
    let fixture = valid_fixture("notes-success", "1.2.3");

    let output = fixture.run_release_check(&["notes", "v1.2.3"]);

    assert_success(&output);
    assert_eq!(
        String::from_utf8(output.stdout).expect("stdout should be utf-8"),
        "### Added\n\n- Release ceremony tooling.\n"
    );
}

#[test]
fn notes_accept_release_candidate_tags_without_suffix_duplication() {
    let fixture = valid_fixture("notes-rc-success", "1.2.3-rc.2");

    let output = fixture.run_release_check(&["notes", "v1.2.3-rc.2"]);

    assert_success(&output);
    assert_eq!(
        String::from_utf8(output.stdout).expect("stdout should be utf-8"),
        "### Added\n\n- Release ceremony tooling.\n"
    );
}

#[test]
fn notes_rejects_unsupported_beta_release_candidate_tags() {
    let fixture = valid_fixture("notes-beta-tag", "1.2.3-beta.1");

    let output = fixture.run_release_check(&["notes", "v1.2.3-beta.1"]);

    assert_failure_contains(
        &output,
        "release version must look like vX.Y.Z or vX.Y.Z-rc.N: v1.2.3-beta.1",
    );
}

#[test]
fn notes_rejects_release_candidate_tags_without_a_numeric_suffix() {
    let fixture = valid_fixture("notes-rc-no-number-tag", "1.2.3-rc");

    let output = fixture.run_release_check(&["notes", "v1.2.3-rc"]);

    assert_failure_contains(
        &output,
        "release version must look like vX.Y.Z or vX.Y.Z-rc.N: v1.2.3-rc",
    );
}

#[test]
fn notes_rejects_unsupported_alpha_release_candidate_tags() {
    let fixture = valid_fixture("notes-alpha-tag", "1.2.3-alpha.2.3");

    let output = fixture.run_release_check(&["notes", "v1.2.3-alpha.2.3"]);

    assert_failure_contains(
        &output,
        "release version must look like vX.Y.Z or vX.Y.Z-rc.N: v1.2.3-alpha.2.3",
    );
}

#[test]
fn notes_rejects_tags_with_noncanonical_numeric_components() {
    let fixture = valid_fixture("notes-noncanonical-tags", "1.2.3");

    for tag in [
        "v01.2.3",
        "v1.02.3",
        "v1.2.03",
        "v1.2.3-rc.01",
        "v1.2.3-rc.0",
    ] {
        let output = fixture.run_release_check(&["notes", tag]);

        assert_failure_contains(
            &output,
            &format!("release version must look like vX.Y.Z or vX.Y.Z-rc.N: {tag}"),
        );
    }
}

#[test]
fn release_rejects_tag_versions_that_do_not_match_workspace_version() {
    let fixture = valid_fixture("release-version-mismatch", "1.2.3");

    let output = fixture.run_release_check(&["release", "v1.2.4"]);

    assert_failure_contains(
        &output,
        "workspace version 1.2.3 does not match tag version 1.2.4",
    );
}

#[test]
fn release_checks_agentd_binary_identity_when_a_binary_is_supplied() {
    let fixture = valid_fixture("release-binary-success", "1.2.3");
    fixture.write(
        "fake-agentd",
        "#!/usr/bin/env sh\nprintf 'agentd 1.2.3\\n'\n",
    );
    fs::set_permissions(
        fixture.root.join("fake-agentd"),
        fs::Permissions::from_mode(0o755),
    )
    .expect("fake binary should be executable");

    let output = fixture.run_release_check(&["release", "v1.2.3", "--agentd-bin", "fake-agentd"]);

    assert_success(&output);
}

#[test]
fn release_rejects_agentd_binary_version_mismatches() {
    let fixture = valid_fixture("release-binary-mismatch", "1.2.3");
    fixture.write(
        "fake-agentd",
        "#!/usr/bin/env sh\nprintf 'agentd 9.9.9\\n'\n",
    );
    fs::set_permissions(
        fixture.root.join("fake-agentd"),
        fs::Permissions::from_mode(0o755),
    )
    .expect("fake binary should be executable");

    let output = fixture.run_release_check(&["release", "v1.2.3", "--agentd-bin", "fake-agentd"]);

    assert_failure_contains(&output, "agentd binary reports");
}

#[test]
fn release_checks_container_label_and_extracted_cli_identity() {
    let fixture = valid_fixture("release-container-success", "1.2.3");
    fixture.write(
        "fake-runtime",
        r#"#!/usr/bin/env sh
set -eu
case "$1" in
  inspect)
    printf '%s\n' "${FAKE_AGENTD_REF:?}"
    ;;
  create)
    printf 'fake-container\n'
    ;;
  cp)
    destination="$3"
    cat >"$destination" <<'EOF'
#!/usr/bin/env sh
printf 'agentd 1.2.3\n'
EOF
    chmod +x "$destination"
    ;;
  rm)
    exit 0
    ;;
  *)
    echo "unexpected fake-runtime command: $*" >&2
    exit 64
    ;;
esac
"#,
    );
    fs::set_permissions(
        fixture.root.join("fake-runtime"),
        fs::Permissions::from_mode(0o755),
    )
    .expect("fake runtime should be executable");

    let output = Command::new("bash")
        .arg(fixture.root.join("scripts/release-check"))
        .args([
            "release",
            "v1.2.3",
            "--container-image",
            "localhost/agentd:v1.2.3",
        ])
        .current_dir(&fixture.root)
        .env(
            "AGENTD_CONTAINER_RUNTIME",
            fixture.root.join("fake-runtime"),
        )
        .env("FAKE_AGENTD_REF", "v1.2.3")
        .output()
        .expect("release-check should run");

    assert_success(&output);
}

#[test]
fn release_accepts_release_candidate_identity_without_suffix_duplication() {
    let fixture = valid_fixture("release-rc-success", "1.2.3-rc.2");
    fixture.write(
        "fake-agentd",
        "#!/usr/bin/env sh\nprintf 'agentd 1.2.3-rc.2\\n'\n",
    );
    fs::set_permissions(
        fixture.root.join("fake-agentd"),
        fs::Permissions::from_mode(0o755),
    )
    .expect("fake binary should be executable");
    fixture.write(
        "fake-runtime",
        r#"#!/usr/bin/env sh
set -eu
case "$1" in
  inspect)
    printf '%s\n' "${FAKE_AGENTD_REF:?}"
    ;;
  create)
    printf 'fake-container\n'
    ;;
  cp)
    destination="$3"
    cat >"$destination" <<'EOF'
#!/usr/bin/env sh
printf 'agentd 1.2.3-rc.2\n'
EOF
    chmod +x "$destination"
    ;;
  rm)
    exit 0
    ;;
  *)
    echo "unexpected fake-runtime command: $*" >&2
    exit 64
    ;;
esac
"#,
    );
    fs::set_permissions(
        fixture.root.join("fake-runtime"),
        fs::Permissions::from_mode(0o755),
    )
    .expect("fake runtime should be executable");

    let output = Command::new("bash")
        .arg(fixture.root.join("scripts/release-check"))
        .args([
            "release",
            "v1.2.3-rc.2",
            "--agentd-bin",
            "fake-agentd",
            "--container-image",
            "localhost/agentd:v1.2.3-rc.2",
        ])
        .current_dir(&fixture.root)
        .env(
            "AGENTD_CONTAINER_RUNTIME",
            fixture.root.join("fake-runtime"),
        )
        .env("FAKE_AGENTD_REF", "v1.2.3-rc.2")
        .output()
        .expect("release-check should run");

    assert_success(&output);
}

#[test]
fn release_rejects_changelog_headings_that_only_regex_match_the_tag_version() {
    let fixture = valid_fixture("release-regex-matched-heading", "1.2.3-rc.2");
    fixture.write(
        "CHANGELOG.md",
        r#"# Changelog

## [Unreleased]

## [1.2.3-rcZ2] — 2026-05-07

### Added

- Release ceremony tooling.
"#,
    );

    let output = fixture.run_release_check(&["release", "v1.2.3-rc.2"]);

    assert_failure_contains(&output, "release heading");
}

#[test]
fn release_heading_lookup_does_not_interpolate_versions_into_extended_regexes() {
    let fixture = valid_fixture("release-heading-regex-shape", "1.2.3");
    let script = fs::read_to_string(fixture.root.join("scripts/release-check"))
        .expect("release-check script should be readable");

    assert!(
        !script.contains("grep -Eq \"^## \\\\[$version\\\\]"),
        "release heading lookup must not interpolate the version into grep -E"
    );
}

#[test]
fn release_rejects_container_label_mismatches() {
    let fixture = valid_fixture("release-container-label-mismatch", "1.2.3");
    fixture.write(
        "fake-runtime",
        "#!/usr/bin/env sh\nif [ \"$1\" = inspect ]; then printf 'v9.9.9\\n'; else exit 64; fi\n",
    );
    fs::set_permissions(
        fixture.root.join("fake-runtime"),
        fs::Permissions::from_mode(0o755),
    )
    .expect("fake runtime should be executable");

    let output = Command::new("bash")
        .arg(fixture.root.join("scripts/release-check"))
        .args([
            "release",
            "v1.2.3",
            "--container-image",
            "localhost/agentd:v1.2.3",
        ])
        .current_dir(&fixture.root)
        .env(
            "AGENTD_CONTAINER_RUNTIME",
            fixture.root.join("fake-runtime"),
        )
        .output()
        .expect("release-check should run");

    assert_failure_contains(&output, "container image label org.tesserine.agentd.ref");
}
